### PR TITLE
Profile update

### PR DESCRIPTION
**Pull request by mediaformat**
- Edit Profile (Display name & Bio)
- Remove models from Avatars collection

### CODE REVIEW

**Review by wmurphyrd — CHANGES_REQUESTED** [review]
## Remove modal

Wow the modal is gorgeous! Really nice touch putting the preview in there, and it works perfectly

image


* I think the dialog::backdrop could use a little more opacity to make it clear the rest of the page is inactive. 
* For the remove/cancel buttons, I'd prefer some gap there to make it harder to misclick, like how the model actions are. Take a look at `.modelActionButtons` class definition
* Could we add a sentence in the dialog explaining the action? with a simple remove action, it would be something like "This will remove the avatar from your collection, but it will not be deleted and could be added back later"
* I also wonder if we should offer a remove & delete option, but this gets more complicated because some avatars in your collection are `Create`d by you, but others can be `Create`d by someone else and `Offer`ed to you. Probably something to revisit later

I get one of these when opening the modal:

```
Warning: Invalid DOM property `class`. Did you mean `className`?
```


## Edit profile

image

Works great. I think we could use some styling touchups.

* For the profile summary textarea, it's small and cramped. There's a custom class on the non-editing version of the summary that would probably resolve this and give it the same size and spacing. 
*  For display name input, low priority but it would be nice if it had the same height as the non-editing version so there wouldn't be any page reflow
* For the save/exit buttons, I'd prefer some gap there to make it harder to misclick, like how the model actions are. Take a look at `.modelActionButtons` class definition
* I also wonder if it is clear enough to the user what parts are editable - the display name definitely has a visible change, but I think the textarea will be very subtle once the size & margins are matched. Do you think we could add some other emphasis like a colored outline or maybe a pencil emoji ?

**Comment by mediaformat** [comment]
# Icon vs outline
Any preference? Can also put icon on the left
Screen Shot 2022-10-14 at 1 24 55 PM
Screen Shot 2022-10-14 at 1 30 25 PM

**Comment by mediaformat** [comment]
> I also wonder if we should offer a remove & delete option

I agree this should be left for later

>Could we add a sentence in the dialog explaining the action? 

Good idea, I've added a description parameter to the dialog component. 

>"This will remove the avatar from your collection, but it will not be deleted and could be added back later"

I'm tempted to shorten this considering the "added back later" part isn't yet implemented. wdyt?

**Review by wmurphyrd — CHANGES_REQUESTED** [review]
Really close here.

1. A couple of nits below,
2. Please [cut a release of immers-client](https://github.com/immers-space/immers-client#creating-a-new-release) and install that new version here so that it will be available when we build the release image
3. Update changelog

**Review by wmurphyrd — APPROVED** [review]

**Pull request merged**
